prompt --application/deployment/install/install_01_tables
begin
--   Manifest
--     INSTALL: INSTALL-01 Tables
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>9252854035907689
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'APP_DEMO'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(10913050000000001)
,p_install_id=>wwv_flow_imp.id(10913044024043292)
,p_name=>'01 Tables'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'prompt =========================================================',
'prompt 01_tables.sql',
'prompt Minimal data model for the demo case',
'prompt =========================================================',
'',
'set define off',
'',
'-------------------------------------------------------------------------------',
'-- Safe drop section to make the script re-runnable',
'-------------------------------------------------------------------------------',
'begin',
'    execute immediate ''drop trigger app_users_bu_trg'';',
'exception',
'    when others then',
'        if sqlcode != -4080 then',
'            raise;',
'        end if;',
'end;',
'/',
'',
'begin',
'    execute immediate ''drop table app_api_event_log cascade constraints purge'';',
'exception',
'    when others then',
'        if sqlcode != -942 then',
'            raise;',
'        end if;',
'end;',
'/',
'',
'begin',
'    execute immediate ''drop table app_user_oauth_clients cascade constraints purge'';',
'exception',
'    when others then',
'        if sqlcode != -942 then',
'            raise;',
'        end if;',
'end;',
'/',
'',
'begin',
'    execute immediate ''drop table app_users cascade constraints purge'';',
'exception',
'    when others then',
'        if sqlcode != -942 then',
'            raise;',
'        end if;',
'end;',
'/',
'',
'-------------------------------------------------------------------------------',
'-- Main application user table',
'-------------------------------------------------------------------------------',
'create table app_users (',
'    id               number generated by default on null as identity,',
'    google_sub       varchar2(255 char) not null,',
'    email            varchar2(320 char),',
'    full_name        varchar2(200 char) not null,',
'    birth_date       date,',
'    phone_number     varchar2(40 char),',
'    status           varchar2(20 char) default ''ACTIVE'' not null,',
'    created_at       timestamp with local time zone default systimestamp not null,',
'    updated_at       timestamp with local time zone default systimestamp not null,',
'    constraint app_users_pk primary key (id),',
'    constraint app_users_uk_google_sub unique (google_sub),',
'    constraint app_users_ck_status check (status in (''ACTIVE'', ''INACTIVE''))',
');',
'',
'create index app_users_ix1 on app_users (email);',
'',
'-------------------------------------------------------------------------------',
'-- Link between the application user and the ORDS OAuth client',
'-- One user can have at most one active client in this demo',
'-------------------------------------------------------------------------------',
'create table app_user_oauth_clients (',
'    id                 number generated by default on null as identity,',
'    app_user_id        number not null,',
'    ords_client_name   varchar2(255 char) not null,',
'    ords_client_id     varchar2(255 char) not null,',
'    active_flag        varchar2(1 char) default ''Y'' not null,',
'    created_at         timestamp with local time zone default systimestamp not null,',
'    constraint app_user_oauth_clients_pk primary key (id),',
'    constraint app_user_oauth_clients_fk1',
'        foreign key (app_user_id) references app_users (id),',
'    constraint app_user_oauth_clients_uk1 unique (ords_client_id),',
'    constraint app_user_oauth_clients_ck1 check (active_flag in (''Y'', ''N''))',
');',
'',
'create unique index app_user_oauth_clients_uix1',
'    on app_user_oauth_clients (',
'        case when active_flag = ''Y'' then app_user_id end',
'    );',
'',
'create index app_user_oauth_clients_ix2 on app_user_oauth_clients (ords_client_name);',
'',
'-------------------------------------------------------------------------------',
'-- Lightweight endpoint diagnostics and identity troubleshooting log',
'-- Optional, but useful to validate actual ORDS runtime behavior',
'-------------------------------------------------------------------------------',
'create table app_api_event_log (',
'    id                    number generated by default on null as identity,',
'    event_type            varchar2(50 char) not null,',
'    event_at              timestamp with local time zone default systimestamp not null,',
'    ords_client_id        varchar2(255 char),',
'    ords_client_name      varchar2(255 char),',
'    current_user_value    varchar2(255 char),',
'    remote_user_value     varchar2(255 char),',
'    remote_ident_value    varchar2(255 char),',
'    client_identifier     varchar2(255 char),',
'    notes                 varchar2(4000 char),',
'    constraint app_api_event_log_pk primary key (id)',
');',
'',
'comment on table app_users is',
'    ''Simple application profile table, identified primarily by google_sub.'';',
'',
'comment on table app_user_oauth_clients is',
'    ''Links an application user to an ORDS OAuth2 client.'';',
'',
'comment on table app_api_event_log is',
'    ''Lightweight log used to diagnose what ORDS propagates to the protected handler.'';',
'',
'-------------------------------------------------------------------------------',
'-- Simple trigger to maintain updated_at',
'-------------------------------------------------------------------------------',
'create or replace trigger app_users_bu_trg',
'before update on app_users',
'for each row',
'begin',
'    :new.updated_at := systimestamp;',
'end;',
'/',
'',
'show errors'))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000004)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'APP_API_EVENT_LOG'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000002)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'APP_USERS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000003)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'APP_USER_OAUTH_CLIENTS'
);
wwv_flow_imp.component_end;
end;
/
