prompt --application/deployment/definition
begin
--   Manifest
--     INSTALL: 100
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>9252854035907689
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'APP_DEMO'
);
wwv_flow_imp_shared.create_install(
 p_id=>wwv_flow_imp.id(10913044024043292)
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(10913050000000001)
,p_install_id=>wwv_flow_imp.id(10913044024043292)
,p_name=>'01 Tables'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>q'!prompt =========================================================
prompt 01_tables.sql
prompt Minimal data model for the demo case
prompt =========================================================

set define off

-------------------------------------------------------------------------------
-- Safe drop section to make the script re-runnable
-------------------------------------------------------------------------------
begin
    execute immediate 'drop trigger app_users_bu_trg';
exception
    when others then
        if sqlcode != -4080 then
            raise;
        end if;
end;
/

begin
    execute immediate 'drop table app_api_event_log cascade constraints purge';
exception
    when others then
        if sqlcode != -942 then
            raise;
        end if;
end;
/

begin
    execute immediate 'drop table app_user_oauth_clients cascade constraints purge';
exception
    when others then
        if sqlcode != -942 then
            raise;
        end if;
end;
/

begin
    execute immediate 'drop table app_users cascade constraints purge';
exception
    when others then
        if sqlcode != -942 then
            raise;
        end if;
end;
/

-------------------------------------------------------------------------------
-- Main application user table
-------------------------------------------------------------------------------
create table app_users (
    id               number generated by default on null as identity,
    google_sub       varchar2(255 char) not null,
    email            varchar2(320 char),
    full_name        varchar2(200 char) not null,
    birth_date       date,
    phone_number     varchar2(40 char),
    status           varchar2(20 char) default 'ACTIVE' not null,
    created_at       timestamp with local time zone default systimestamp not null,
    updated_at       timestamp with local time zone default systimestamp not null,
    constraint app_users_pk primary key (id),
    constraint app_users_uk_google_sub unique (google_sub),
    constraint app_users_ck_status check (status in ('ACTIVE', 'INACTIVE'))
);

create index app_users_ix1 on app_users (email);

-------------------------------------------------------------------------------
-- Link between the application user and the ORDS OAuth client
-- One user can have at most one active client in this demo
-------------------------------------------------------------------------------
create table app_user_oauth_clients (
    id                 number generated by default on null as identity,
    app_user_id        number not null,
    ords_client_name   varchar2(255 char) not null,
    ords_client_id     varchar2(255 char) not null,
    active_flag        varchar2(1 char) default 'Y' not null,
    created_at         timestamp with local time zone default systimestamp not null,
    constraint app_user_oauth_clients_pk primary key (id),
    constraint app_user_oauth_clients_fk1
        foreign key (app_user_id) references app_users (id),
    constraint app_user_oauth_clients_uk1 unique (ords_client_id),
    constraint app_user_oauth_clients_ck1 check (active_flag in ('Y', 'N'))
);

create unique index app_user_oauth_clients_uix1
    on app_user_oauth_clients (
        case when active_flag = 'Y' then app_user_id end
    );

create index app_user_oauth_clients_ix2 on app_user_oauth_clients (ords_client_name);

-------------------------------------------------------------------------------
-- Lightweight endpoint diagnostics and identity troubleshooting log
-- Optional, but useful to validate actual ORDS runtime behavior
-------------------------------------------------------------------------------
create table app_api_event_log (
    id                    number generated by default on null as identity,
    event_type            varchar2(50 char) not null,
    event_at              timestamp with local time zone default systimestamp not null,
    ords_client_id        varchar2(255 char),
    ords_client_name      varchar2(255 char),
    current_user_value    varchar2(255 char),
    remote_user_value     varchar2(255 char),
    remote_ident_value    varchar2(255 char),
    client_identifier     varchar2(255 char),
    notes                 varchar2(4000 char),
    constraint app_api_event_log_pk primary key (id)
);

comment on table app_users is
    'Simple application profile table, identified primarily by google_sub.';

comment on table app_user_oauth_clients is
    'Links an application user to an ORDS OAuth2 client.';

comment on table app_api_event_log is
    'Lightweight log used to diagnose what ORDS propagates to the protected handler.';

-------------------------------------------------------------------------------
-- Simple trigger to maintain updated_at
-------------------------------------------------------------------------------
create or replace trigger app_users_bu_trg
before update on app_users
for each row
begin
    :new.updated_at := systimestamp;
end;
/

show errors!'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000002)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'TABLE'
,p_object_name=>'APP_USERS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000003)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'TABLE'
,p_object_name=>'APP_USER_OAUTH_CLIENTS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000004)
,p_script_id=>wwv_flow_imp.id(10913050000000001)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'TABLE'
,p_object_name=>'APP_API_EVENT_LOG'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(10913050000000005)
,p_install_id=>wwv_flow_imp.id(10913044024043292)
,p_name=>'02 Packages'
,p_sequence=>20
,p_script_type=>'INSTALL'
,p_script_clob=>q'!prompt =========================================================
prompt 02_packages.sql
prompt PL/SQL packages for the demo case
prompt =========================================================

set define off

-------------------------------------------------------------------------------
-- APEX session context helpers
-------------------------------------------------------------------------------
create or replace package app_security_ctx as
    function app_user_id return number;
    function google_sub return varchar2;
    function email return varchar2;
    function full_name return varchar2;
end app_security_ctx;
/

create or replace package body app_security_ctx as
    function get_app_item (
        p_item_name in varchar2
    ) return varchar2
    is
        l_value varchar2(4000 char);
    begin
        begin
            l_value := apex_util.get_session_state(p_item_name);
        exception
            when others then
                l_value := null;
        end;

        return l_value;
    end get_app_item;

    function app_user_id return number is
    begin
        return to_number(get_app_item('G_APP_USER_ID'));
    exception
        when value_error then
            return null;
    end app_user_id;

    function google_sub return varchar2 is
    begin
        return get_app_item('G_GOOGLE_SUB');
    end google_sub;

    function email return varchar2 is
    begin
        return get_app_item('G_SOCIAL_EMAIL');
    end email;

    function full_name return varchar2 is
    begin
        return get_app_item('G_SOCIAL_FULL_NAME');
    end full_name;
end app_security_ctx;
/

show errors

-------------------------------------------------------------------------------
-- Main API package for the demo case
-------------------------------------------------------------------------------
create or replace package app_user_api as
    subtype t_varchar2 is varchar2(32767 char);

    type t_identity_rec is record (
        google_sub      app_users.google_sub%type,
        email           app_users.email%type,
        full_name       app_users.full_name%type
    );

    type t_credentials_rec is record (
        app_user_id        app_users.id%type,
        email              app_users.email%type,
        full_name          app_users.full_name%type,
        phone_number       app_users.phone_number%type,
        ords_client_name   app_user_oauth_clients.ords_client_name%type,
        ords_client_id     app_user_oauth_clients.ords_client_id%type,
        ords_client_secret varchar2(4000 char),
        created_now_flag   varchar2(1 char)
    );

    type t_me_rec is record (
        app_user_id        app_users.id%type,
        email              app_users.email%type,
        full_name          app_users.full_name%type,
        phone_number       app_users.phone_number%type,
        ords_client_id     app_user_oauth_clients.ords_client_id%type,
        ords_client_name   app_user_oauth_clients.ords_client_name%type,
        created_at         app_user_oauth_clients.created_at%type
    );

    function normalize_phone (
        p_phone_number in varchar2
    ) return varchar2;

    procedure validate_profile (
        p_full_name     in varchar2,
        p_birth_date    in date,
        p_phone_number  in varchar2
    );

    function find_user_by_google_sub (
        p_google_sub in varchar2
    ) return app_users%rowtype;

    function upsert_social_user (
        p_google_sub in varchar2,
        p_email      in varchar2,
        p_full_name  in varchar2
    ) return number;

    function has_active_client (
        p_app_user_id in number
    ) return varchar2;

    procedure complete_registration (
        p_google_sub            in varchar2,
        p_email                 in varchar2,
        p_full_name             in varchar2,
        p_birth_date            in date,
        p_phone_number          in varchar2,
        p_out_app_user_id       out nocopy number,
        p_out_client_name       out nocopy varchar2,
        p_out_client_id         out nocopy varchar2,
        p_out_client_secret     out nocopy varchar2,
        p_out_created_now_flag  out nocopy varchar2
    );

    procedure get_credentials_for_display (
        p_app_user_id           in number,
        p_out_client_name       out nocopy varchar2,
        p_out_client_id         out nocopy varchar2
    );

    procedure write_runtime_log (
        p_event_type          in varchar2,
        p_ords_client_id      in varchar2,
        p_ords_client_name    in varchar2,
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2,
        p_client_identifier   in varchar2,
        p_notes               in varchar2 default null
    );

    function resolve_client_id_from_runtime (
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2
    ) return varchar2;

    function get_me_by_runtime (
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2
    ) return t_me_rec;
end app_user_api;
/

create or replace package body app_user_api as
    g_ords_role_name constant varchar2(128 char) := 'app_me_role';
    g_ords_priv_name constant varchar2(128 char) := 'app.me.privilege';

    function normalize_phone (
        p_phone_number in varchar2
    ) return varchar2
    is
    begin
        return regexp_replace(trim(p_phone_number), '[^0-9+]', '');
    end normalize_phone;

    procedure validate_profile (
        p_full_name     in varchar2,
        p_birth_date    in date,
        p_phone_number  in varchar2
    )
    is
    begin
        if p_full_name is null or length(trim(p_full_name)) < 3 then
            raise_application_error(-20001, 'Enter a valid full name.');
        end if;

        if p_birth_date is null then
            raise_application_error(-20002, 'Enter a birth date.');
        end if;

        if p_birth_date > trunc(sysdate) then
            raise_application_error(-20003, 'Birth date cannot be in the future.');
        end if;

        if add_months(trunc(sysdate), -12 * 120) > p_birth_date then
            raise_application_error(-20004, 'Birth date is outside the expected range for this demo.');
        end if;

        if p_phone_number is null or length(normalize_phone(p_phone_number)) < 8 then
            raise_application_error(-20005, 'Enter a valid phone number.');
        end if;
    end validate_profile;

    function find_user_by_google_sub (
        p_google_sub in varchar2
    ) return app_users%rowtype
    is
        l_user app_users%rowtype;
    begin
        select *
          into l_user
          from app_users
         where google_sub = p_google_sub;

        return l_user;
    exception
        when no_data_found then
            return l_user;
    end find_user_by_google_sub;

    function upsert_social_user (
        p_google_sub in varchar2,
        p_email      in varchar2,
        p_full_name  in varchar2
    ) return number
    is
        l_app_user_id app_users.id%type;
    begin
        if p_google_sub is null then
            raise_application_error(-20010, 'google_sub was not returned by the social authentication flow.');
        end if;

        merge into app_users dst
        using (
            select p_google_sub as google_sub,
                   p_email      as email,
                   nvl(trim(p_full_name), 'Google User') as full_name
              from dual
        ) src
           on (dst.google_sub = src.google_sub)
        when matched then update
             set dst.email = coalesce(src.email, dst.email),
                 dst.full_name = case
                                     when dst.full_name is null or dst.full_name = 'Google User'
                                     then src.full_name
                                     else dst.full_name
                                 end
        when not matched then insert (
             google_sub, email, full_name, status
        ) values (
             src.google_sub, src.email, src.full_name, 'ACTIVE'
        );

        select id
          into l_app_user_id
          from app_users
         where google_sub = p_google_sub;

        return l_app_user_id;
    end upsert_social_user;

    function has_active_client (
        p_app_user_id in number
    ) return varchar2
    is
        l_dummy varchar2(1 char);
    begin
        select 'Y'
          into l_dummy
          from app_user_oauth_clients
         where app_user_id = p_app_user_id
           and active_flag = 'Y';

        return 'Y';
    exception
        when no_data_found then
            return 'N';
    end has_active_client;

    procedure ensure_ords_role is
    begin
        begin
            ords.create_role(p_role_name => g_ords_role_name);
        exception
            when others then
                if sqlcode not in (-20001, -955) then
                    raise;
                end if;
        end;
    end ensure_ords_role;

    procedure provision_ords_client (
        p_app_user_id           in number,
        p_google_sub            in varchar2,
        p_email                 in varchar2,
        p_out_client_name       out nocopy varchar2,
        p_out_client_id         out nocopy varchar2,
        p_out_client_secret     out nocopy varchar2,
        p_out_created_now_flag  out nocopy varchar2
    )
    is
        l_client_name    varchar2(255 char);
        l_existing_id    app_user_oauth_clients.ords_client_id%type;
        l_existing_name  app_user_oauth_clients.ords_client_name%type;
    begin
        begin
            select ords_client_id, ords_client_name
              into l_existing_id, l_existing_name
              from app_user_oauth_clients
             where app_user_id = p_app_user_id
               and active_flag = 'Y';

            p_out_client_name      := l_existing_name;
            p_out_client_id        := l_existing_id;
            p_out_client_secret    := null;
            p_out_created_now_flag := 'N';
            return;
        exception
            when no_data_found then
                null;
        end;

        l_client_name := substr(
            'APPUSR_' || p_app_user_id || '_' || replace(lower(rawtohex(utl_raw.cast_to_raw(p_google_sub))), ' ', ''),
            1,
            120
        );

        ensure_ords_role;

        oauth.create_client(
            p_name            => l_client_name,
            p_grant_type      => 'client_credentials',
            p_owner           => user,
            p_description     => 'OAuth client created by the APEX self-service flow for app_user_id=' || p_app_user_id,
            p_support_email   => nvl(p_email, 'noreply@example.com'),
            p_privilege_names => g_ords_priv_name
        );

        oauth.grant_client_role(
            p_client_name => l_client_name,
            p_role_name   => g_ords_role_name
        );

        select client_id, client_secret
          into p_out_client_id, p_out_client_secret
          from user_ords_clients
         where name = l_client_name;

        insert into app_user_oauth_clients (
            app_user_id,
            ords_client_name,
            ords_client_id,
            active_flag
        ) values (
            p_app_user_id,
            l_client_name,
            p_out_client_id,
            'Y'
        );

        p_out_client_name      := l_client_name;
        p_out_created_now_flag := 'Y';
    exception
        when dup_val_on_index then
            raise_application_error(-20020, 'An active OAuth client already exists for this user.');
    end provision_ords_client;

    procedure complete_registration (
        p_google_sub            in varchar2,
        p_email                 in varchar2,
        p_full_name             in varchar2,
        p_birth_date            in date,
        p_phone_number          in varchar2,
        p_out_app_user_id       out nocopy number,
        p_out_client_name       out nocopy varchar2,
        p_out_client_id         out nocopy varchar2,
        p_out_client_secret     out nocopy varchar2,
        p_out_created_now_flag  out nocopy varchar2
    )
    is
        l_phone_number app_users.phone_number%type;
    begin
        validate_profile(
            p_full_name    => p_full_name,
            p_birth_date   => p_birth_date,
            p_phone_number => p_phone_number
        );

        p_out_app_user_id := upsert_social_user(
            p_google_sub => p_google_sub,
            p_email      => p_email,
            p_full_name  => p_full_name
        );

        l_phone_number := normalize_phone(p_phone_number);

        update app_users
           set full_name    = trim(p_full_name),
               birth_date   = p_birth_date,
               phone_number = l_phone_number,
               email        = coalesce(p_email, email),
               status       = 'ACTIVE'
         where id = p_out_app_user_id;

        provision_ords_client(
            p_app_user_id           => p_out_app_user_id,
            p_google_sub            => p_google_sub,
            p_email                 => p_email,
            p_out_client_name       => p_out_client_name,
            p_out_client_id         => p_out_client_id,
            p_out_client_secret     => p_out_client_secret,
            p_out_created_now_flag  => p_out_created_now_flag
        );
    end complete_registration;

    procedure get_credentials_for_display (
        p_app_user_id           in number,
        p_out_client_name       out nocopy varchar2,
        p_out_client_id         out nocopy varchar2
    )
    is
    begin
        select ords_client_name, ords_client_id
          into p_out_client_name, p_out_client_id
          from app_user_oauth_clients
         where app_user_id = p_app_user_id
           and active_flag = 'Y';
    end get_credentials_for_display;

    procedure write_runtime_log (
        p_event_type          in varchar2,
        p_ords_client_id      in varchar2,
        p_ords_client_name    in varchar2,
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2,
        p_client_identifier   in varchar2,
        p_notes               in varchar2 default null
    )
    is
        pragma autonomous_transaction;
    begin
        insert into app_api_event_log (
            event_type,
            ords_client_id,
            ords_client_name,
            current_user_value,
            remote_user_value,
            remote_ident_value,
            client_identifier,
            notes
        ) values (
            p_event_type,
            p_ords_client_id,
            p_ords_client_name,
            p_current_user_value,
            p_remote_user_value,
            p_remote_ident_value,
            p_client_identifier,
            p_notes
        );

        commit;
    exception
        when others then
            rollback;
    end write_runtime_log;

    function resolve_client_id_from_runtime (
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2
    ) return varchar2
    is
        l_client_identifier varchar2(255 char);
        l_client_id         varchar2(255 char);
    begin
        l_client_identifier := sys_context('userenv', 'client_identifier');

        if l_client_identifier is not null then
            begin
                select c.client_id
                  into l_client_id
                  from user_ords_clients c
                 where c.client_id = l_client_identifier;
                return l_client_id;
            exception
                when no_data_found then
                    null;
            end;

            begin
                select c.client_id
                  into l_client_id
                  from user_ords_clients c
                 where c.name = l_client_identifier;
                return l_client_id;
            exception
                when no_data_found then
                    null;
            end;
        end if;

        if p_current_user_value is not null then
            begin
                select c.client_id
                  into l_client_id
                  from user_ords_clients c
                 where c.client_id = p_current_user_value
                    or c.name = p_current_user_value;
                return l_client_id;
            exception
                when no_data_found then
                    null;
            end;
        end if;

        if p_remote_user_value is not null then
            begin
                select c.client_id
                  into l_client_id
                  from user_ords_clients c
                 where c.client_id = p_remote_user_value
                    or c.name = p_remote_user_value;
                return l_client_id;
            exception
                when no_data_found then
                    null;
            end;
        end if;

        if p_remote_ident_value is not null then
            begin
                select c.client_id
                  into l_client_id
                  from user_ords_clients c
                 where c.client_id = p_remote_ident_value
                    or c.name = p_remote_ident_value;
                return l_client_id;
            exception
                when no_data_found then
                    null;
            end;
        end if;

        return null;
    end resolve_client_id_from_runtime;

    function get_me_by_runtime (
        p_current_user_value  in varchar2,
        p_remote_user_value   in varchar2,
        p_remote_ident_value  in varchar2
    ) return t_me_rec
    is
        l_me                t_me_rec;
        l_client_id         varchar2(255 char);
        l_client_name       varchar2(255 char);
        l_client_identifier varchar2(255 char);
    begin
        l_client_identifier := sys_context('userenv', 'client_identifier');
        l_client_id := resolve_client_id_from_runtime(
            p_current_user_value => p_current_user_value,
            p_remote_user_value  => p_remote_user_value,
            p_remote_ident_value => p_remote_ident_value
        );

        if l_client_id is null then
            write_runtime_log(
                p_event_type         => 'ME_LOOKUP_FAILED',
                p_ords_client_id     => null,
                p_ords_client_name   => null,
                p_current_user_value => p_current_user_value,
                p_remote_user_value  => p_remote_user_value,
                p_remote_ident_value => p_remote_ident_value,
                p_client_identifier  => l_client_identifier,
                p_notes              => 'Unable to resolve client_id from the ORDS runtime context.'
            );

            raise_application_error(-20030, 'Unable to identify the authenticated OAuth client.');
        end if;

        select u.id,
               u.email,
               u.full_name,
               u.phone_number,
               c.ords_client_id,
               c.ords_client_name,
               c.created_at
          into l_me.app_user_id,
               l_me.email,
               l_me.full_name,
               l_me.phone_number,
               l_me.ords_client_id,
               l_me.ords_client_name,
               l_me.created_at
          from app_users u
          join app_user_oauth_clients c
            on c.app_user_id = u.id
         where c.ords_client_id = l_client_id
           and c.active_flag = 'Y';

        begin
            select name
              into l_client_name
              from user_ords_clients
             where client_id = l_client_id;
        exception
            when no_data_found then
                l_client_name := l_me.ords_client_name;
        end;

        write_runtime_log(
            p_event_type         => 'ME_LOOKUP_OK',
            p_ords_client_id     => l_client_id,
            p_ords_client_name   => l_client_name,
            p_current_user_value => p_current_user_value,
            p_remote_user_value  => p_remote_user_value,
            p_remote_ident_value => p_remote_ident_value,
            p_client_identifier  => l_client_identifier,
            p_notes              => 'Lookup completed successfully.'
        );

        return l_me;
    end get_me_by_runtime;
end app_user_api;
/

show errors!'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000006)
,p_script_id=>wwv_flow_imp.id(10913050000000005)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE'
,p_object_name=>'APP_SECURITY_CTX'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000007)
,p_script_id=>wwv_flow_imp.id(10913050000000005)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'APP_SECURITY_CTX'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000008)
,p_script_id=>wwv_flow_imp.id(10913050000000005)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE'
,p_object_name=>'APP_USER_API'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000009)
,p_script_id=>wwv_flow_imp.id(10913050000000005)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'APP_USER_API'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(10913050000000010)
,p_install_id=>wwv_flow_imp.id(10913044024043292)
,p_name=>'03 ORDS REST'
,p_sequence=>30
,p_script_type=>'INSTALL'
,p_script_clob=>q'!prompt =========================================================
prompt 03_ords_rest.sql
prompt ORDS REST, role, privilege, and endpoint setup
prompt =========================================================

set define off

-------------------------------------------------------------------------------
-- 1. REST-enable the schema
-- Run once. If the schema is already enabled, keep or adjust as needed.
-------------------------------------------------------------------------------
begin
    ords.enable_schema(
        p_enabled             => true,
        p_schema              => user,
        p_url_mapping_type    => 'BASE_PATH',
        p_url_mapping_pattern => lower(user),
        p_auto_rest_auth      => false
    );
    commit;
exception
    when others then
        if sqlcode not in (-20000, -955) then
            raise;
        end if;
end;
/

-------------------------------------------------------------------------------
-- 2. ORDS role used by the demo endpoint
-------------------------------------------------------------------------------
begin
    ords.create_role(
        p_role_name => 'app_me_role'
    );
    commit;
exception
    when others then
        if sqlcode not in (-20001, -955) then
            raise;
        end if;
end;
/

-------------------------------------------------------------------------------
-- 3. Module / template / handler
-- Expected base path: /ords/<schema-mapping>/api/v1/me
-------------------------------------------------------------------------------
begin
    ords.delete_module(
        p_module_name => 'api'
    );
    commit;
exception
    when others then
        null;
end;
/

begin
    ords.define_module(
        p_module_name    => 'api',
        p_base_path      => 'api/',
        p_items_per_page => 0,
        p_status         => 'PUBLISHED',
        p_comments       => 'APEX + Google + ORDS OAuth2 client credentials demo case'
    );

    ords.define_template(
        p_module_name => 'api',
        p_pattern     => 'v1/me'
    );

    ords.define_handler(
        p_module_name => 'api',
        p_pattern     => 'v1/me',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_mimes_allowed => 'application/json',
        p_source      => q'[
declare
    l_me                app_user_api.t_me_rec;
    l_current_user      varchar2(255 char) := :current_user;
    l_remote_user       varchar2(255 char) := :remote_user;
    l_remote_ident      varchar2(255 char) := owa_util.get_cgi_env('REMOTE_IDENT');
begin
    owa_util.mime_header('application/json', false);
    htp.p('Cache-Control: no-store');
    owa_util.http_header_close;

    l_me := app_user_api.get_me_by_runtime(
        p_current_user_value => l_current_user,
        p_remote_user_value  => l_remote_user,
        p_remote_ident_value => l_remote_ident
    );

    apex_json.open_object;
    apex_json.write('app_user_id',     l_me.app_user_id);
    apex_json.write('email',           l_me.email);
    apex_json.write('full_name',       l_me.full_name);
    apex_json.write('phone_number',    l_me.phone_number);
    apex_json.write('ords_client_id',  l_me.ords_client_id);
    apex_json.write('ords_client_name',l_me.ords_client_name);
    apex_json.write('created_at',      to_char(l_me.created_at, 'YYYY-MM-DD"T"HH24:MI:SS'));
    apex_json.close_object;
exception
    when others then
        apex_json.open_object;
        apex_json.write('error', 'unable_to_resolve_authenticated_client');
        apex_json.write('message', sqlerrm);
        apex_json.write('current_user', l_current_user);
        apex_json.write('remote_user', l_remote_user);
        apex_json.write('remote_ident', l_remote_ident);
        apex_json.write('client_identifier', sys_context('userenv', 'client_identifier'));
        apex_json.close_object;
end;
        ]'
    );

    commit;
end;
/

-------------------------------------------------------------------------------
-- 4. Optional diagnostics endpoint
-- Helps validate what ORDS actually propagates at runtime
-------------------------------------------------------------------------------
begin
    ords.define_template(
        p_module_name => 'api',
        p_pattern     => 'v1/runtime-diagnostics'
    );

    ords.define_handler(
        p_module_name => 'api',
        p_pattern     => 'v1/runtime-diagnostics',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_mimes_allowed => 'application/json',
        p_source      => q'[
begin
    owa_util.mime_header('application/json', false);
    htp.p('Cache-Control: no-store');
    owa_util.http_header_close;

    apex_json.open_object;
    apex_json.write('current_user', :current_user);
    apex_json.write('remote_user', :remote_user);
    apex_json.write('remote_ident', owa_util.get_cgi_env('REMOTE_IDENT'));
    apex_json.write('client_identifier', sys_context('userenv', 'client_identifier'));
    apex_json.write('session_user', sys_context('userenv', 'session_user'));
    apex_json.write('current_schema', sys_context('userenv', 'current_schema'));
    apex_json.close_object;
end;
        ]'
    );

    commit;
end;
/

-------------------------------------------------------------------------------
-- 5. Privilege protecting the endpoint
-------------------------------------------------------------------------------
begin
    ords.delete_privilege(
        p_name => 'app.me.privilege'
    );
    commit;
exception
    when others then
        null;
end;
/

begin
    ords.define_privilege(
        p_privilege_name => 'app.me.privilege',
        p_roles          => owa.vc_arr('app_me_role'),
        p_patterns       => owa.vc_arr('/api/v1/me', '/api/v1/runtime-diagnostics'),
        p_modules        => owa.vc_arr('api'),
        p_label          => 'Access app me endpoint',
        p_description    => 'Allows access to the /api/v1/me endpoint'
    );
    commit;
end;
/

prompt =========================================================
prompt Expected URLs
prompt Token endpoint:    /ords/<schema-mapping>/oauth/token
prompt Resource endpoint: /ords/<schema-mapping>/api/v1/me
prompt Diag endpoint:     /ords/<schema-mapping>/api/v1/runtime-diagnostics
prompt =========================================================!'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(10913050000000011)
,p_install_id=>wwv_flow_imp.id(10913044024043292)
,p_name=>'04 APEX Helper Package'
,p_sequence=>40
,p_script_type=>'INSTALL'
,p_script_clob=>q'!prompt =========================================================
prompt 04_apex_helpers.sql
prompt Optional APEX helper package for post-authentication
prompt =========================================================

set define off

create or replace package app_apex_auth as
    procedure post_login;
end app_apex_auth;
/

create or replace package body app_apex_auth as
    procedure post_login is
        l_google_sub  varchar2(255 char);
        l_app_user_id number;
    begin
        l_google_sub := apex_util.get_session_state('G_GOOGLE_SUB');

        if l_google_sub is null then
            raise_application_error(
                -20050,
                'G_GOOGLE_SUB is null. Check the Social Sign-In attribute mapping.'
            );
        end if;

        begin
            select id
              into l_app_user_id
              from app_users
             where google_sub = l_google_sub;

            apex_util.set_session_state('G_APP_USER_ID', l_app_user_id);
        exception
            when no_data_found then
                apex_util.set_session_state('G_APP_USER_ID', null);
        end;
    end post_login;
end app_apex_auth;
/

show errors!'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000012)
,p_script_id=>wwv_flow_imp.id(10913050000000011)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE'
,p_object_name=>'APP_APEX_AUTH'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(10913050000000013)
,p_script_id=>wwv_flow_imp.id(10913050000000011)
,p_object_owner=>'APP_DEMO'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'APP_APEX_AUTH'
);
wwv_flow_imp.component_end;
end;
/
