prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/google_oauth_cred.sql
@@workspace/credentials/facebook_oauth_credential.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/g_app_user_id.sql
@@application/shared_components/logic/application_items/g_auth_notice_attempt_provider.sql
@@application/shared_components/logic/application_items/g_auth_notice_code.sql
@@application/shared_components/logic/application_items/g_auth_notice_email.sql
@@application/shared_components/logic/application_items/g_auth_notice_existing_provider.sql
@@application/shared_components/logic/application_items/g_auth_notice_message.sql
@@application/shared_components/logic/application_items/g_auth_provider.sql
@@application/shared_components/logic/application_items/g_creds_created_now.sql
@@application/shared_components/logic/application_items/g_external_subject.sql
@@application/shared_components/logic/application_items/g_google_sub.sql
@@application/shared_components/logic/application_items/g_ords_client_id.sql
@@application/shared_components/logic/application_items/g_ords_client_name.sql
@@application/shared_components/logic/application_items/g_ords_client_secret.sql
@@application/shared_components/logic/application_items/g_social_email.sql
@@application/shared_components/logic/application_items/g_social_full_name.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/google_login.sql
@@application/shared_components/security/authentications/custom_login.sql
@@application/shared_components/security/authentications/facebook_login.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00020.sql
@@application/pages/page_00040.sql
@@application/pages/page_00100.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_01_tables.sql
@@application/deployment/install/install_02_packages.sql
@@application/deployment/install/install_03_ords_rest.sql
@@application/deployment/install/install_04_apex_helper_package.sql
@@application/deployment/install/install_08_multi_login_evolution.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
